---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.name}}
  labels:
    app: {{.Values.app}}
spec:
  minReadySeconds: {{.Values.minReadySeconds}}
  replicas: {{.Values.replicas}}
  selector:
    matchLabels:
      app: {{.Values.app}}
  template:
    metadata:
      labels:
        app: {{.Values.app}}
    spec:
        containers:
          - name: {{.Values.containers.name}}
            image: {{.Values.containers.image}}
            ports:
              - containerPort: {{.Values.containers.ports.containerPort}}
            resources:
              requests:
                cpu: 300m
                memory: 64Mi
              limits:
                cpu: 350m
                memory: 128Mi
