{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  annotations:
{{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
{{- end }}
  labels:
{{- range $key, $value := .Values.ingress.labels }}
    {{ $key }}: {{ $value }}
{{- end }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  rules:
    - http:
        paths:
{{- range .Values.ingress.rules }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ .backendService.name }}
                port:
                  number: {{ .backendService.port }}
{{- end }}
{{- end }}
