
{{- range .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}-svc
spec:
  type: {{ .type }}
  selector:
    app: {{ .selector.app }}
  ports:
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
{{- end }}

