

name: deployment
app: app-deploy
minReadySeconds: 5
replicas: 5
containers:
  name: web
  image: nginx:1.27
  ports:
    containerPort: 80
service:
  name: deploy-service
  selector:
    app: app-deploy
  type: NodePort
  ports:
    port: 80
    targetPort: 80


